"""add fields to savings_goals for UI (description, category, priority, monthly_contribution)

Revision ID: e864d19360e2
Revises: 13b60d6fed84
Create Date: 2025-10-15 23:24:05.318476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e864d19360e2'
down_revision = '13b60d6fed84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.create_index('idx_savings_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_savings_priority', ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_index('idx_savings_priority')
        batch_op.drop_index('idx_savings_deadline')
        batch_op.drop_column('monthly_contribution')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
